INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana Grey', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Ação');
INSERT INTO tb_genre (name) VALUES ('Animação');
INSERT INTO tb_genre (name) VALUES ('Aventura');
INSERT INTO tb_genre (name) VALUES ('Drama');
INSERT INTO tb_genre (name) VALUES ('Ficção científica');
INSERT INTO tb_genre (name) VALUES ('Terror');

INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Tenet', 'O tempo acaba.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wzJRB4MKi3yK138bJyuL9nx47y6.jpg', 'Armado com apenas uma palavra – Tenet – e lutando pela sobrevivência do mundo inteiro, o Protagonista viaja através de um mundo crepuscular de espionagem internacional em uma missão que irá desenrolar em algo para além do tempo real.', 5);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('O Esquadrão Suicida', 'Eles estão loucos... para salvar o mundo.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg', 'Os supervilões Harley Quinn (Margot Robbie), Bloodsport (Idris Elba), Peacemaker (John Cena) e uma coleção de malucos condenados da prisão de Belle Reve juntam-se à super-secreta e super-obscura Força Tarefa X, enquanto são deixados na remota ilha de Corto Maltese para combater o inimigo.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Godzilla vs. Kong', 'Um dos dois cairá.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg', 'Em uma época em que os monstros andam na Terra, a luta da humanidade por seu futuro coloca Godzilla e Kong em rota de colisão que verá as duas forças mais poderosas da natureza no planeta se confrontarem em uma batalha espetacular para as idades. Enquanto Monarch embarca em uma missão perigosa em terreno desconhecido e descobre pistas sobre as origens dos Titãs, uma conspiração humana ameaça tirar as criaturas, boas e más, da face da terra para sempre.', 5);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Vingadores: Ultimato', 'O fim de uma era!', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg', 'Após os eventos devastadores de "Vingadores: Guerra Infinita", o universo está em ruínas devido aos esforços do Titã Louco, Thanos. Com a ajuda de aliados remanescentes, os Vingadores devem se reunir mais uma vez a fim de desfazer as ações de Thanos e restaurar a ordem no universo de uma vez por todas, não importando as consequências.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Space Jam', 'Um Novo Legado.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/xhbXRitgTCzYSZbwhHRj56wLlIz.jpg', 'O superastro do basquete LeBron James se junta à gangue Looney Tunes para derrotar o Goon Squad e salvar seu filho.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Nem um Passo em Falso', 'Confiança é uma armadilha', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/ok7RdHhVngnwkvKj09tvtOvypG.jpg', 'Um grupo de pequenos criminosos em Detroit na década de 1950 são contratados por uma pessoa anônima para roubar um importante documento. Mas quando seu plano dá terrivelmente errado, o grupo descobre que se envolveu em uma rede de conspirações muito maior do que poderiam imaginar.', 4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('A Guerra do Amanhã ', 'A luta pelo amanhã começa hoje.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yizL4cEKsVvl17Wc1mGEIrQtM2F.jpg', 'Em 2051, a humanidade está perdendo uma guerra global contra uma espécie mortal de alienígenas. Para garantir a sobrevivência dos humanos, soldados e civis do presente são transportados para o futuro e se juntam à luta, entre eles Dan Forester, um pai de família determinado a salvar o mundo para sua filha.', 5);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Um Lugar Silencioso - Parte II', 'Apenas o silêncio não será suficiente.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/z2UtGA1WggESspi6KOXeo66lvLx.jpg', 'Logo após os acontecimentos mortais, até mesmo dentro de casa, a família Abbott precisa agora encarar o terror mundo afora, continuando a lutar para sobreviver em silêncio. Obrigados a se aventurar pelo desconhecido, eles rapidamente percebem que as criaturas que caçam pelo som não são as únicas ameaças que os observam pelo caminho de areia.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Mulher-Maravilha 1984', 'Uma nova era de maravilhas começa.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/srYya1ZlI97Au4jUYAktDe3avyA.jpg', 'Em 1984, Diana Prince entra em conflito com dois inimigos formidáveis, Maxwell Lord e a Mulher-Leopardo, enquanto reencontra misteriosamente com seu antigo interesse amoroso Steve Trevor.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('G.I. Joe Origens: Snake Eyes ', 'Todo guerreiro tem um começo.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/aO9Nnv9GdwiPdkNO79TISlQ5bbG.jpg', 'Depois de salvar a vida de seu herdeiro aparente, o tenaz solitário Snake Eyes é recebido em um antigo clã japonês chamado Arashikage, onde aprende os caminhos do guerreiro ninja. Mas, quando os segredos de seu passado forem revelados, a honra e a lealdade de Snake Eyes serão testadas - mesmo que isso signifique perder a confiança das pessoas mais próximas a ele.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Sociedade da Justiça: 2ª Guerra Mundial', 'A luta pela justiça é a maior batalha de todos os tempos.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/8LHSDyRizQ4kQz5rEHPKyXPvMG3.jpg', 'A viagem relaxante de Barry Allen para Metrópolis está prestes a dar errado. Enquanto corre para ajudar em uma luta inesperada, o Flash rompe as barreiras do tempo, e acaba parando no meio da Segunda Guerra Mundial. É lá que o Flash conhece a Mulher Maravilha e a equipe supersecreta dela, conhecida como Sociedade da Justiça da América. Testemunhe os rumos turbulentos da guerra, combates envolventes e a velocidade da honra enquanto o Flash luta para voltar ao seu próprio tempo!', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Jogador N° 1', 'Uma aventura muito além do mundo real.', 2018, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/5a7lMDn3nAj2ByO0X1fg6BhUphR.jpg', 'Num futuro distópico, situado em 2044, Wade Watts, como o resto da humanidade, prefere a realidade virtual do jogo OASIS ao mundo real. No jogo, seus usuários devem descobrir a chave de um quebra-cabeça diabólico, baseado na cultura do final do século XX, para conquistar um prêmio de valor inestimável. Para vencê-lo, porém, Watts terá de abandonar a existência virtual e ceder a uma vida de amor e realidade da qual sempre tentou fugir.', 5);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Mortal Kombat', 'Get over here.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg', 'Nova aventura baseada no videogame Mortal Kombat. Na história, um jovem que nunca treinou artes marciais acaba envolvido em um gigantesco torneio de luta envolvendo guerreiros da Terra e lutadores e outras dimensões.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('O Poderoso Chefinho 2: Negócios da Família', 'O recesso acabou.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/akwg1s7hV5ljeSYFfkw7hTHjVqk.jpg', 'Tim Templeton e seu irmão mais novo Ted, o famoso Boss Baby, tornaram-se adultos, vivem por conta própria, Tim se tornou um homem de família organizado e Ted é o chefe de um grande fundo especulativo. Mas a chegada de um novo Boss Baby, com uma abordagem totalmente nova e estratégia inovadora, está prestes a unir os irmãos inimigos ... e inspirar um novo modelo nos assuntos familiares. Tim e sua esposa Carole moram no subúrbio, onde ele cuida da casa enquanto ela cozinha a panela. Eles têm dois filhos: Tabitha, uma menina de 7 anos extremamente inteligente, e Tina, sua adorável recém-nascida. Tabitha, a primeira da classe em uma escola para superdotados, adora o tio Ted e sonha em seguir seus passos, o que preocupa muito Tim, que teme perder a infância por trabalhar tanto.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Piratas do Caribe: Navegando em Águas Misteriosas', 'Movido pela aventura, navegando no desconhecido.', 2011, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/uzIGtyS6bbnJzGsPL93WCF1FWm8.jpg', 'O passado do capitão Jack Sparrow volta a alcançá-lo quando ele cruza com Angelica, uma bonita pirata que Jack, um dia, amou e depois abandonou. Ela, então, o força a acompanhá-la ao navio Vingança da Rainha Ana, do famoso Barba Negra. Junto com uma tripulação de zumbis, o trio parte em busca da lendária Fonte da Juventude. Mas o rival de Jack, Barbossa, também cobiça a fonte, assim como um navio espanhol.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Bumblebee', 'Toda aventura tem um começo.', 2018, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/17nDJQsGVim6oows2TlN98UacbO.jpg', 'Refugiado em um ferro-velho na Califórnia, Bumblebee, machucado e sem condição de uso, é encontrado e consertado pela jovem Charlie. Quando Bee ganha vida, porém, ela percebe que seu novo amigo é bem mais do que um simples automóvel.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('O Hobbit: A Batalha dos Cinco Exércitos', 'O capítulo decisivo.', 2014, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/bVmSXNgH1gpHYTDyF9Q826YwJT5.jpg', 'O dragão Smaug lança sua fúria ardente contra a Cidade do Lago que fica próxima da montanha de Erebor. Bard consegue derrotá-lo, mas, rapidamente, sem a ameaça do dragão, inicia-se uma batalha pelo controle de Erebor e sua riqueza. Os anões, liderados por Thorin, adentram a montanha e estão dispostos a impedir a entrada de elfos, anões e orcs. Bilbo Bolseiro e Gandalf tentam impedir a guerra.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Um Lugar Silencioso', 'Regra nº 1: não faça barulho. Regra nº 2: nunca deixe o caminho. Regra nº 3: Vermelho significa corra.', 2018, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/iD8g4vLN0gnsaOP28oGcww0yhGH.jpg', 'Em uma fazenda dos Estados Unidos, uma família do meio-oeste é perseguida por uma entidade fantasmagórica assustadora. Para se protegerem, eles devem permanecer em silêncio absoluto, a qualquer custo, pois o perigo é ativado pela percepção do som.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Viúva Negra', 'Ela cansou de fugir de seu passado.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg', 'Natasha Romanoff "Viúva Negra" precisa confrontar partes de sua história quando surge uma conspiração perigosa ligada ao seu passado. Perseguida por uma força que não irá parar até derrotá-la, Natasha terá que lidar com sua antiga vida de espiã, e também reencontrar membros de sua família que deixou para trás antes de se tornar parte dos Vingadores.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Invocação do Mal 2', 'A próxima história real baseada nos casos de Ed e Lorraine Warren.', 2016, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/4mfFtlGeInPrQVm1hpv7th02yjx.jpg', 'Sete anos após os eventos de Invocação do Mal (2013), Lorraine (Vera Farmiga) e Ed Warren (Patrick Wilson) desembarcam na Inglaterra para ajudar uma família atormentada por uma manifestação poltergeist na filha. A trama é baseada no caso Enfield Poltergeist, registrado no final da década de 1970.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Monster Hunter', 'Junte-se à caçada.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/z8TvnEVRenMSTemxYZwLGqFofgF.jpg', 'Baseado no jogo da Capcom chamado Monster Hunter, a tenente Artemis e seus soldados são transportados para um novo mundo. Lá, eles se envolvem em batalhas imponentes, buscando desesperadamente a sobrevivência contra bestas gigantes portadoras de habilidades surreais.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Invocação do Mal 3', 'O caso demoníaco que chocou a América.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/qi6Edc1OPcyENecGtz8TF0DUr9e.jpg', 'Um dos casos mais sensacionais de seus arquivos começa com a luta pela alma de um garoto e depois os leva para além de qualquer coisa que já tenham visto. Esse caso marcou a primeira vez na história dos Estados Unidos em que um suspeito de assassinato alegou possessão demoníaca como defesa.', 6);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('O Espião Inglês', 'Baseado na incrível história real de um empresário que se tornou espião.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/3pIqd1hgZ2xqzWEyiYp4blqE9Fi.jpg', 'Durante a Guerra Fria, diversos civis atuaram como espiões para impedir o avanço soviético no mundo. Greville Wynne, um engenheiro elétrico britânico, foi um desses homens recrutados pelo Serviço de Inteligência Militar Britânico, O MI5. Através de informações cruciais obtidas por uma de suas fontes, Wynne conseguiu determinar o fim da Crise dos Mísseis de Cuba, em 1962.', 4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Paternidade', 'Dores de cabeça e muitas fraldas sujas.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/miOnymJ0dN2psWBB8Vleo3fUyrc.jpg', 'Neste filme inspirado em uma história real, um pai viúvo lida com dúvidas, medos, decepções e mamadeiras ao assumir a tarefa de criar sua filha sozinho.', 4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Infiltrado', 'Um exército de apenas um homem.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9DZlZvgh9dIGcri79hv3KtHiq5K.jpg', 'Harry, conhecido apenas como H, é um homem misterioso que trabalha para uma empresa de carros-fortes e movimenta grandes quantias de dinheiro pela cidade de Los Angeles. Quando, ao impedir um assalto, ele surpreende a todos com suas habilidades de combate, suas verdadeiras intenções começam a ser questionadas e um plano maior é revelado.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Legado Explosivo', 'Nunca impeça um homem de fazer a coisa certa.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2M2JxEv3HSpjnZWjY9NOdGgfUd.jpg', 'Um ladrão de banco resolve mudar de vida e se tornar uma pessoa honesta quando se apaixona por uma mulher que trabalha em uma instalação de armazenamento, um lugar onde ele esconde todo o dinheiro que rouba. Mas fica cada vez mais difícil limpar seu nome quando ele passa a ser investigado por um agente corrupto do FBI.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Jungle Cruise', 'A madição nos confins da selva.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7WJjFviFBffEJvkAms4uWwbcVUk.jpg', 'O destemido capitão Frank Wolff e a intrépida pesquisadora Lily Houghton se aventuram pela Amazônia a bordo da peculiar embarcação La Quila. Determinados a encontrar uma árvore cujos poderes de cura podem mudar o futuro da medicina, nem mesmo as águas perigosas e as forças sobrenaturais que enfrentam pelo caminho poderão detê-los. Mas os riscos aumentam ainda mais conforme os segredos da árvore se revelam, o destino de Lily e Frank e também de toda a humanidade está em jogo.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Um Milagre Inesperado', 'A verdadeira história de um herói improvável.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2dWWf6qjVU0TklCUKCUra1Yqfz3.jpg', 'Após um trágico acidente, uma mulher encontra forças para viver quando sua família resgata e cuida de um pássaro ferido. Baseado numa inspiradora história real.', 4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('O Rei Leão', 'O Rei Retornou.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg', 'Simba é um jovem leão cujo destino é se tornar o rei da selva. Entretanto, uma armadilha elaborada por seu tio Scar faz com que Mufasa, o atual rei, morra ao tentar salvar o filhote. Consumido pela culpa, Simba deixa o reino rumo a um local distante, onde encontra amigos que o ensinam a mais uma vez ter prazer pela vida.', 2);

INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme!', 1, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Curti demais! Excelente!', 5, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Muito top!', 3, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Sensacional!', 2, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Great movie!!', 7, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Recomendo esse ótimo filme!', 12, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Efeitos especiais fantásticos!', 15, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('O filme tão esperado por todos! Top das galáxias!', 4, 2);
